language: node_js
node_js:
  - 8.9.4
install: npm install
script: gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: "www.christianrenewilliams.us"
  skip_cleanup: true
  acl: public_read
  local_dir: public
  region: us-east-2
